### ISSUE TITLE
ACP error on install

### ISSUE THREAD

**Issue by teebling** [avatharbe/QuickStyle#3]
Hey Paybas,

I'm getting an error trying to install this on 3.3:

![Screenshot 2020-08-01 at 22 56 17](https://user-images.githubusercontent.com/49092979/89111161-4ba51580-d44a-11ea-8a93-592152295048.png)

I am able to delete data, but when I try and re-enable the extension it throws the same exception.

**Comment by ghost** [comment]
I just got the same error.


![error](https://user-images.githubusercontent.com/17615050/92159243-f1e59180-ede1-11ea-8efe-5a98b7c17c57.png)

**Comment by Galixte** [comment]
Hi @Sajaki,

could you fix this issue, please?

Regards.

**Comment by Galixte** [comment]
Fixed here: https://github.com/Sajaki/QuickStyle/pull/4.

**Comment by avandenberghe** [comment]
fixed
